name: Email Copilot Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read

jobs:
  run:
    name: Copilot Usage
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/copilot-usage@main
        id: usage
        with:
          organization: ${{ secrets.ORG }}
          github-token: ${{ secrets.TOKEN }}
      - uses: austenstone/job-summary-to-pdf@v1.0
        id: pdf
        with:
          name: copilot-usage
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          from: ${{ secrets.EMAIL }}
          to: ${{ secrets.EMAIL }} # Recipient email
          subject: "Copilot Usage Report (${{ steps.usage.outputs.since }} - ${{ steps.usage.outputs.until }})"
          body: "Attached is the Copilot Usage Report for ${{ steps.usage.outputs.since }} - ${{ steps.usage.outputs.until }}!"
          attachments: ${{ steps.pdf.outputs.pdf-file }}