name: Email Copilot Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Sunday at midnight (00:00).
permissions:
  contents: read

jobs:
  run:
    name: Copilot Usage
    runs-on: ubuntu-latest
    steps:
      # - uses: austenstone/copilot-usage@main
      #   id: usage
      #   with:
      #     enterprise: 'secorp'
      #     github-token: ${{ secrets.SECORP }}
      # - uses: austenstone/job-summary@v2.0
      #   id: pdf
      #   with:
      #     name: copilot-usage
      - uses: dawidd6/action-send-mail@v3
        with:
          # server_address: smtp.gmail.com
          # server_port: 465
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.OUTLOOK_USERNAME }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          from: ${{ secrets.OUTLOOK_USERNAME }}
          to: ${{ secrets.OUTLOOK_USERNAME }} # Recipient email
          subject: "Copilot Usage Report"
          body: |
           Hello
