name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Copilot Usage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          organization: ${{ secrets.ORG }}
          github-token: ${{ secrets.TOKEN }}